# Generated by Django 4.2.6 on 2023-11-01 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mision', '0002_rename_misiones_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial_misiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mision.task')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
