# Generated by Django 4.2.6 on 2023-11-10 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mision', '0003_historial_misiones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntos_usuario',
            name='puntos',
            field=models.IntegerField(default=0),
        ),
    ]
